name: DelphiGenAI – CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Affiche les infos du runner pour debug
        run: |
          echo ─────────────── Runner Info ───────────────
          echo RUNNER_NAME   = %RUNNER_NAME%
          echo RUNNER_OS     = %RUNNER_OS%
          echo RUNNER_LABELS = %RUNNER_LABELS%
          echo ────────────────────────────────────────────

      - name: Vérifie la présence de dcc64.exe
        run: |
          if exist "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\dcc64.exe" (
            echo dcc64.exe trouvé
          ) else (
            echo *** dcc64.exe introuvable *** & exit /b 1
          )

      - name: Build avec dcc64 (Win64 Release)
        run: |
          call "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"
          dcc64.exe -B OpenAITest.dpr