name: DelphiGenAI – CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Compilation Delphi (Win64 Release)
        shell: cmd
        run: |
          cd D:\
          cd D:\2026-developpement\OpenAI

