on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Compilation Delphi (Win64 Release)
        run: |
          cmd.exe /C "cd /d D:\2026-developpement\OpenAI && call \"C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat\" && dcc64.exe -B OpenAITest.dpr"
