name: DelphiGenAI – CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Copier le dossier de travail externe
        shell: cmd
        run: |
          xcopy /E /I "D:\2026-developpement\OpenAI" "%GITHUB_WORKSPACE%\OpenAI"

      - name: Compiler le projet Delphi
        shell: cmd
        run: |
          cd /d "%GITHUB_WORKSPACE%\OpenAI"
          call "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"
          dcc64.exe -B OpenAITest.dpr

      - name: Upload de l’artefact
        uses: actions/upload-artifact@v3
        with:
          name: OpenAITest-Binaries
          path: |
            "%GITHUB_WORKSPACE%\OpenAI\Win64\OpenAITest.exe"
            "%GITHUB_WORKSPACE%\OpenAI\Win64\*.dll"