name: DelphiGenAI – build non-régression

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, Windows, X64 ]   # <- les labels de TON runner
    timeout-minutes: 15

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v4

      # ----- Win64 Release ----------------------------------------------------
      - name: Build Win64 Release
        run: |
          call "%BDS%\bin\rsvars.bat"
          "%BDS%\bin\MSBuild.exe" OpenAITest.dproj ^
            /p:Config=Release ^
            /p:Platform=Win64 ^
            /m

      # ----- Win32 Debug ------------------------------------------------------
      - name: Build Win32 Debug
        run: |
          call "%BDS%\bin\rsvars.bat"
          "%BDS%\bin\MSBuild.exe" OpenAITest.dproj ^
            /p:Config=Debug ^
            /p:Platform=Win32 ^
            /m
